name: Commit a version change internal
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-major-version:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/_commit-version-change.yml
    with:
      version-type: major
      create-feature-docs: false
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-minor-version:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/_commit-version-change.yml
    with:
      version-type: minor
      create-feature-docs: false
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-patch-version:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/_commit-version-change.yml
    with:
      version-type: patch
      create-feature-docs: false
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}
