name: PNPM CI

on:
  workflow_call:
    inputs:
      run-tests:
        description: "Include test runs"
        required: false
        default: true
        type: boolean
      os:
        description: "The operating systems to run the workflow on"
        required: false
        default: '["ubuntu-latest"]' # Lol this is stupid!
        type: string

permissions:
  contents: read

jobs:
  source-code-ci-steps:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }} # VERY stupid!
    if: ${{ github.head_ref != 'alex-up-bot/change-major-version' && github.head_ref != 'alex-up-bot/change-minor-version' && github.head_ref != 'alex-up-bot/change-patch-version' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use PNPM
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Run linting checks
        run: pnpm run lint

      - name: Run tests
        if: ${{ inputs.run-tests == true }}
        run: pnpm test

  source-code-ci:
    needs: source-code-ci-steps
    runs-on: ubuntu-latest
    if: always()
    env:
      CI_STATUS: ${{ needs.source-code-ci-steps.result }}
    steps:
      - name: Report on any matrix failures
        run: |
          if [ "$CI_STATUS" != "success" ]; then
            exit 1
          fi

  version-change-ci:
    uses: ./.github/workflows/version-change-ci.yml
